-- Per-(user, guild) cached profile used by the @-mention reply path so the LLM does not
-- need to call getCallerInfo / getCallerModerationPermissions on every interaction. The
-- bot prefetches this from JDA the first time a user mentions it in a guild, and a daily
-- cron refreshes name/role/permission columns. `personality_summary` is generated by a
-- small LLM call on creation and refreshed every N exchanges (see UserInfoService).
--
-- These cached permission flags are advisory only — destructive moderation tools in
-- DiscordTools.executeMod() still re-check authority live against JDA before acting.
CREATE TABLE users_info (
    id                  BIGSERIAL    PRIMARY KEY,
    user_id             VARCHAR(64)  NOT NULL,
    guild_id            VARCHAR(64)  NOT NULL,
    effective_name      VARCHAR(128) NOT NULL,
    highest_role_id     VARCHAR(64),
    highest_role_name   VARCHAR(128),
    administrator       BOOLEAN      NOT NULL DEFAULT FALSE,
    kick_members        BOOLEAN      NOT NULL DEFAULT FALSE,
    ban_members         BOOLEAN      NOT NULL DEFAULT FALSE,
    moderate_members    BOOLEAN      NOT NULL DEFAULT FALSE,
    manage_messages     BOOLEAN      NOT NULL DEFAULT FALSE,
    manage_channel      BOOLEAN      NOT NULL DEFAULT FALSE,
    manage_guild        BOOLEAN      NOT NULL DEFAULT FALSE,
    personality_summary TEXT,
    exchanges_count     INT          NOT NULL DEFAULT 0,
    last_refreshed_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_users_info_user_guild
    ON users_info (user_id, guild_id);
